// Mapping of event URL slug (from events.json) to DB eventId
const EVENT_ID_MAP = {
  "code-busters": "TECH_CB",
  "red-tech": "TECH_RT",
  "robo-wars": "TECH_RW",
  "robo-race": "TECH_RR",
  "robo-pick-n-place": "TECH_RP",
  "intelliquest": "TECH_IQ",
  "brainstorm-battle": "TECH_BS",
  "circuit-crafter": "TECH_CC",
  "electrofix-challenge": "TECH_EC",
  "junkyard-wars": "TECH_JW",
  "ai-quizathon": "TECH_AQ",
  "ecoai-challenge": "TECH_EA",
  "project-model-exhibition": "TECH_PM",
  "coding-ladder": "TECH_CL",
  "web-wizard": "TECH_WW",
  "cyber-shield": "TECH_CS",
  "app-attack": "TECH_AA",
  "data-dash": "TECH_DD",
  "design-dash": "TECH_DS",
  "load-bridging": "TECH_LB",
  "poster-presentation": "CRE_PP",
  "face-painting": "CRE_FP",
  "pot-painting": "CRE_PT",
  "photography": "CRE_PH",
  "greenearth-challenge": "CRE_GE",
  "cricket": "CRE_CR",
  "need-for-speed": "CRE_NF",
  "bgmi": "CRE_BG",
  "free-fire": "CRE_FF",
  "technical-debate": "CRE_TD",
  "group-ramp-walk": "CUL_GW",
  "solo-ramp-walk": "CUL_SW",
  "treasure-hunt": "CUL_TH",
  "tug-of-war": "CUL_TW",
  "sudoku": "CUL_SD",
  "fire-free-cooking": "CUL_FC",
  "solo-singing": "CUL_SS",
  "solo-dance": "CUL_SDN",
  "group-singing": "CUL_GS",
  "group-dance": "CUL_GD",
  "rap": "CUL_RP",
  "beat-boxing": "CUL_BB",
  "poetry": "CUL_PT",
  "story-telling": "CUL_ST",
  "art-attack": "CUL_AA"
};

module.exports = {
  EVENT_ID_MAP
};
